set(CMAKE_ASM_JWASM_COMPILER_INIT jwasm)

if(NOT CMAKE_ASM_JWASM_COMPILER)
	find_program(CMAKE_ASM_JWASM_COMPILER jwasm)
endif(NOT CMAKE_ASM_JWASM_COMPILER)

set(ASM_DIALECT "_JWASM")
include(CMakeDetermineASMCompiler)
set(ASM_DIALECT)
